
import java.util.ArrayList;
import java.util.Calendar;
import java.sql.Timestamp;
import java.util.Collections;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author acv
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private String currentSemester; 
    
    public MainFrame() {
        initComponents();
        rebuildSemesterComboBoxes();
        rebuildStudentComboBoxes();
        rebuildCourseComboBoxes();
        
        updateCourseDisplay();
    }
    
    public void rebuildSemesterComboBoxes()
    {
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
        
        if (semesters.size() > 0)
        {
            currentSemesterLabel.setText(semesters.get(0));
        }
        else
        {
            currentSemesterLabel.setText("None, add a semester.");
            currentSemester = "None";
        }
    }
    public void rebuildCourseComboBoxes()
    {
        ArrayList<CourseEntry> Courses = CourseQueries.getAllCourses();
        
        
        if(currentSemesterComboBox.getSelectedItem() == null){
            
        }
        else{
        ArrayList<CourseEntry> Courseh = CourseQueries.getAllCourses(currentSemesterComboBox.getSelectedItem().toString());
        scheduleCourseCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(Courseh.toArray()));
        DropCourseCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(Courseh.toArray()));
        DisplayCourseListOfStudentsComboBox.setModel(new javax.swing.DefaultComboBoxModel(Courseh.toArray()));
        }
        
        String s = (String) currentSemesterComboBox.getSelectedItem();
        StudentEntry student = (StudentEntry) DropCourseStudentComboBox1.getSelectedItem();
        if(student != null){
        String ID = student.getStudentID();
        
        ArrayList<ScheduleEntry> classes = ScheduleQueries.getScheduleByStudent(s,ID);
        //ArrayList<ScheduleEntry> classes = ScheduleQueries.getScheduleByStudent(s,ID);
        ArrayList<CourseEntry> cs = new ArrayList<CourseEntry>();
        for(ScheduleEntry i: classes){
            cs.add(new CourseEntry(s,i.getCourseCode(),CourseQueries.getDescription(i.getCourseCode()),CourseQueries.getCourseSeats(s,i.getCourseCode())));
        }
        DropCourseStudentCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(cs.toArray()));
        }
    }
    public void updateCourseDisplay(){
        String smstr = (String) currentSemesterComboBox.getSelectedItem();
        String displayy = "";
        ArrayList<CourseEntry> coursess = CourseQueries.getAllCourses(smstr);
        for(CourseEntry cours: coursess){
            displayy += cours.getCourseCode()+ " - "+cours.getDescription()+" "+cours.getSeats()+" seats";
            displayy+= "\n";
        }
        displayCoursesTextArea.setText(displayy);
    }
    public void rebuildStudentComboBoxes(){
        ArrayList<StudentEntry> students = StudentQueries.getAllStudents();
        scheduleCourseStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        displayScheduleStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        DropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        DropCourseStudentComboBox1.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addSemesterTextfield = new javax.swing.JTextField();
        addSemesterSubmitButton = new javax.swing.JButton();
        addSemesterStatusLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addCourseSubmitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        addCourseCourseCodeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addCourseDescriptionTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addCourseSeatsSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        addCourseStatusLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addStudentSubmitButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        addStudentStudentIDTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addStudentFirstNameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addStudentLastNameTextField = new javax.swing.JTextField();
        addStudentStatusLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        DisplayCourseListOfStudentsComboBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        displayCourseListOfStudentsTextArea = new javax.swing.JTextArea();
        DisplayCourseListOfStudentsDisplayButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        DropStudentComboBox = new javax.swing.JComboBox<>();
        DropStudentButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        DropStudentTextArea = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        DropCourseCourseComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        DropCourseDropButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        DropCourseTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        scheduleCourseStudentComboBox = new javax.swing.JComboBox<>();
        scheduleCourseSubmitButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        scheduleCourseCourseComboBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        scheduleCourseStatusLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        displayScheduleDisplayButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        displayScheduleStudentComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayScheduleTextArea = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayCoursesTextArea = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        DropCourseStudentComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        DropCourseStudentCourseComboBox = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        DropCourseStudentTextArea = new javax.swing.JTextArea();
        DropCourseStudentSubmitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        currentSemesterLabel = new javax.swing.JLabel();
        currentSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Scheduler");

        jLabel3.setText("Semester Name:");

        addSemesterTextfield.setColumns(20);

        addSemesterSubmitButton.setText("Submit");
        addSemesterSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterSubmitButtonActionPerformed(evt);
            }
        });

        addSemesterStatusLabel.setText("                                                   ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(addSemesterSubmitButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addSemesterSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(addSemesterStatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Semester", jPanel3);

        addCourseSubmitButton.setText("Submit");
        addCourseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseSubmitButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Course Code:");

        addCourseCourseCodeTextField.setColumns(12);
        addCourseCourseCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseCourseCodeTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Decription:");

        addCourseDescriptionTextField.setColumns(20);
        addCourseDescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseDescriptionTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Number of Seats:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(addCourseStatusLabel))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCourseCourseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCourseSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addCourseSubmitButton)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addCourseCourseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(addCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(addCourseSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(addCourseSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCourseStatusLabel)
                .addGap(38, 38, 38))
        );

        jTabbedPane2.addTab("Add Course", jPanel4);

        addStudentSubmitButton.setText("Submit");
        addStudentSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentSubmitButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("StudentID:");

        addStudentStudentIDTextField.setColumns(10);

        jLabel9.setText("First Name:");

        addStudentFirstNameTextField.setColumns(15);
        addStudentFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentFirstNameTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Last Name:");

        addStudentLastNameTextField.setColumns(15);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentStatusLabel)
                    .addComponent(addStudentSubmitButton)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addStudentStudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addStudentFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addStudentLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addStudentStudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(addStudentFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(addStudentLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(addStudentSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(addStudentStatusLabel)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Student", jPanel5);

        jLabel13.setText("Course:");

        DisplayCourseListOfStudentsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DisplayCourseListOfStudentsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCourseListOfStudentsComboBoxActionPerformed(evt);
            }
        });

        displayCourseListOfStudentsTextArea.setEditable(false);
        displayCourseListOfStudentsTextArea.setColumns(20);
        displayCourseListOfStudentsTextArea.setLineWrap(true);
        displayCourseListOfStudentsTextArea.setRows(5);
        displayCourseListOfStudentsTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(displayCourseListOfStudentsTextArea);

        DisplayCourseListOfStudentsDisplayButton.setText("Display");
        DisplayCourseListOfStudentsDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCourseListOfStudentsDisplayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(DisplayCourseListOfStudentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(DisplayCourseListOfStudentsDisplayButton))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(DisplayCourseListOfStudentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayCourseListOfStudentsDisplayButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Display Course List OF Students", jPanel9);

        jLabel17.setText("Student:");

        DropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropStudentButton.setText("Drop");
        DropStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropStudentButtonActionPerformed(evt);
            }
        });

        DropStudentTextArea.setEditable(false);
        DropStudentTextArea.setColumns(20);
        DropStudentTextArea.setLineWrap(true);
        DropStudentTextArea.setRows(5);
        DropStudentTextArea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(DropStudentTextArea);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addGap(29, 29, 29)
                .addComponent(DropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(DropStudentButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(DropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropStudentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Drop Student", jPanel10);

        DropCourseCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Course:");

        DropCourseDropButton.setText("Drop Course");
        DropCourseDropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropCourseDropButtonActionPerformed(evt);
            }
        });

        DropCourseTextArea.setEditable(false);
        DropCourseTextArea.setColumns(20);
        DropCourseTextArea.setLineWrap(true);
        DropCourseTextArea.setRows(5);
        DropCourseTextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(DropCourseTextArea);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DropCourseCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(DropCourseDropButton))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DropCourseCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(DropCourseDropButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Drop Course", jPanel11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        jLabel12.setText("Student:");

        scheduleCourseStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        scheduleCourseSubmitButton.setText("Schedule Course");
        scheduleCourseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleCourseSubmitButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Courses:");

        scheduleCourseCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scheduleCourseSubmitButton)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scheduleCourseStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scheduleCourseCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scheduleCourseStatusLabel)
                            .addComponent(jLabel16))))
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(scheduleCourseStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(scheduleCourseCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(scheduleCourseSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(scheduleCourseStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(25, 25, 25))
        );

        jTabbedPane3.addTab("Schedule Course", jPanel6);

        displayScheduleDisplayButton.setText("Display");
        displayScheduleDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayScheduleDisplayButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Student:");

        displayScheduleStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        displayScheduleTextArea.setEditable(false);
        displayScheduleTextArea.setColumns(50);
        displayScheduleTextArea.setLineWrap(true);
        displayScheduleTextArea.setRows(5);
        displayScheduleTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(displayScheduleTextArea);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(displayScheduleDisplayButton))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayScheduleStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(displayScheduleStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(displayScheduleDisplayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane3.addTab("Display Schedule", jPanel7);

        displayCoursesTextArea.setEditable(false);
        displayCoursesTextArea.setColumns(20);
        displayCoursesTextArea.setLineWrap(true);
        displayCoursesTextArea.setRows(5);
        displayCoursesTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(displayCoursesTextArea);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Display Courses", jPanel8);

        jLabel18.setText("Student:");

        DropCourseStudentComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DropCourseStudentComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropCourseStudentComboBox1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Course;");

        DropCourseStudentCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropCourseStudentTextArea.setColumns(20);
        DropCourseStudentTextArea.setRows(5);
        jScrollPane6.setViewportView(DropCourseStudentTextArea);

        DropCourseStudentSubmitButton.setText("Drop");
        DropCourseStudentSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropCourseStudentSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(DropCourseStudentComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DropCourseStudentCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(DropCourseStudentSubmitButton)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(DropCourseStudentComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(DropCourseStudentCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropCourseStudentSubmitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Drop Course", jPanel12);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Student", jPanel2);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setText("Current Semester: ");

        currentSemesterLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        currentSemesterLabel.setText("           ");

        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        currentSemesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentSemesterComboBoxActionPerformed(evt);
            }
        });

        changeSemesterButton.setText("Change Semester");
        changeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentSemesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(changeSemesterButton)
                                .addGap(80, 80, 80)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentSemesterLabel)
                    .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSemesterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentSemesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentSemesterComboBoxActionPerformed
        // TODO add your handling code here:
        //rebuildSemesterComboBoxes();
    }//GEN-LAST:event_currentSemesterComboBoxActionPerformed

    private void changeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSemesterButtonActionPerformed
        // TODO add your handling code here:
        currentSemesterLabel.setText(currentSemesterComboBox.getSelectedItem().toString());
        updateCourseDisplay();
        rebuildCourseComboBoxes();
        String s = (String) currentSemesterComboBox.getSelectedItem();
        StudentEntry student = (StudentEntry) DropCourseStudentComboBox1.getSelectedItem();
        String ID = student.getStudentID();
        ArrayList<ScheduleEntry> classes = ScheduleQueries.getScheduleByStudent(s,ID);
        ArrayList<CourseEntry> cs = new ArrayList<CourseEntry>();
        for(ScheduleEntry i: classes){
            cs.add(new CourseEntry(s,i.getCourseCode(),CourseQueries.getDescription(i.getCourseCode()),CourseQueries.getCourseSeats(s,i.getCourseCode())));
        }
        //DropCourseStudentCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(cs.toArray()));
        
    }//GEN-LAST:event_changeSemesterButtonActionPerformed

    private void displayScheduleDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayScheduleDisplayButtonActionPerformed
        // TODO add your handling code here:

        String show = "";
        StudentEntry stu = (StudentEntry) displayScheduleStudentComboBox.getSelectedItem();
        String s = (String) currentSemesterComboBox.getSelectedItem();
        ArrayList<ScheduleEntry> entrys = ScheduleQueries.getScheduleByStudent(s,stu.getStudentID());
        for(ScheduleEntry ENtry: entrys){
            String code = ENtry.getCourseCode();
            CourseQueries.getDescription(code);
            show+= (ENtry.getCourseCode()  + " - " + ENtry.getStatus());
            show += "\n";
        }
        displayScheduleTextArea.setText(show);

    }//GEN-LAST:event_displayScheduleDisplayButtonActionPerformed

    private void scheduleCourseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleCourseSubmitButtonActionPerformed
        // TODO add your handling code here:

        CourseEntry c = (CourseEntry) scheduleCourseCourseComboBox.getSelectedItem();
        StudentEntry s = (StudentEntry) scheduleCourseStudentComboBox.getSelectedItem();

        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        Integer d = ScheduleQueries.getScheduledStudentCount(currentSemesterComboBox.getSelectedItem().toString(),c.getCourseCode());
        if(c.getSeats() > d){
            ScheduleEntry sch = new ScheduleEntry(currentSemesterComboBox.getSelectedItem().toString(),c.getCourseCode(),s.getStudentID(),"scheduled",currentTimestamp);
            ScheduleQueries.addScheduleEntry(sch);
            scheduleCourseStatusLabel.setText("Course Scheduled: " +s.getLastName()+", " +s.getFirstName() + " - "+ c.getCourseCode());
        }
        else{
            ScheduleEntry sch = new ScheduleEntry(currentSemesterComboBox.getSelectedItem().toString(),c.getCourseCode(),s.getStudentID(),"waitlisted",currentTimestamp);
            ScheduleQueries.addScheduleEntry(sch);
            scheduleCourseStatusLabel.setText("Course WaitListed: "+s.getLastName()+", " +s.getFirstName() +" - "+ c.getCourseCode());
        }
        //rebuildCourseComboBoxes();

    }//GEN-LAST:event_scheduleCourseSubmitButtonActionPerformed

    private void DropCourseDropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropCourseDropButtonActionPerformed
        // TODO add your handling code here:
        CourseEntry dc = (CourseEntry) DropCourseCourseComboBox.getSelectedItem();
        String ds = (String) currentSemesterComboBox.getSelectedItem();
        ArrayList<ArrayList<StudentEntry>> es = CourseQueries.DropCourse(ds,dc.getCourseCode());
        rebuildCourseComboBoxes();
        String dropDisplay = "Scheduled Students Dropped from the Course: \n";
        //currentSemesterLabel.setText(es.get(0).toString());
        for(StudentEntry s: es.get(0)){
            dropDisplay += s.getLastName() + ", " + s.getFirstName() + " " + (s.getStudentID() + "\n");
        }
        dropDisplay+=("Waitlisted Students Dropped from the Course: \n");
        for(StudentEntry s: es.get(1)){
            dropDisplay += s.getLastName() + ", " + s.getFirstName() + " " + (s.getStudentID() + "\n");
        }
        DropCourseTextArea.setText(dropDisplay);
    }//GEN-LAST:event_DropCourseDropButtonActionPerformed

    private void DropStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropStudentButtonActionPerformed
        // TODO add your handling code here:
        String textDisplay = "";
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        StudentEntry s = (StudentEntry) DropStudentComboBox.getSelectedItem();
        textDisplay += s.getLastName() + ", " + s.getFirstName() + " " + s.getStudentID() + " has been dropped from the list of students.\n";
        for(String curSemester: semesters){

            textDisplay += "\nFor Semester " + curSemester + ": \n";

            String sem = (String) currentSemesterComboBox.getSelectedItem();
            ArrayList<ScheduleEntry> classes = ScheduleQueries.getScheduleByStudent(curSemester,s.getStudentID());

            StudentQueries.DropStudent(s.getStudentID(),curSemester);

            rebuildStudentComboBoxes();

            ArrayList<ScheduleEntry> listed = new ArrayList<>();
            for(ScheduleEntry clas: classes){
                if(clas.getStatus().equals("waitlisted")){
                    textDisplay += s.getLastName()+ ", " + s.getFirstName() + " Has been dropped from the waitlist for " + clas.getCourseCode() + "\n";
                }
                else{
                    textDisplay += s.getLastName()+ ", " + s.getFirstName() + " Has been dropped from " + clas.getCourseCode() + "\n";
                }
                ArrayList<ScheduleEntry> l = ScheduleQueries.getScheduledStudentsByCourse(curSemester,clas.getCourseCode());
                for(ScheduleEntry i: l){
                    if(i.getStatus().equals("waitlisted")){
                        listed.add(i);
                    }
                }
                Collections.sort(listed);
                if(listed.size() > 0){

                    ScheduleQueries.MoveOffWaitlist(listed.get(0));
                    StudentEntry addedStudent = StudentQueries.getStudentByID(listed.get(0).getStudentID());
                    textDisplay += addedStudent.getLastName() + ", " + addedStudent.getFirstName() + " "+addedStudent.getStudentID() +" has been scheduled into " + clas.getCourseCode() + "\n";

                    ScheduleQueries.addScheduleEntry(new ScheduleEntry(listed.get(0).getSemester(),listed.get(0).getCourseCode(),listed.get(0).getStudentID(),"scheduled",listed.get(0).getTimestamp()));
                }
            }
        }
        DropStudentTextArea.setText(textDisplay);
        /*
        CourseEntry c = (CourseEntry) DropStudentComboBox.getSelectedItem();
        ArrayList<ScheduleEntry> l = ScheduleQueries.getScheduledStudentsByCourse(sem,c.getCourseCode());
        //ArrayList<ScheduleEntry> listed = new ArrayList<>();
        //ArrayList<ScheduleEntry> listed = new ArrayList<>();
        for(ScheduleEntry i: l){
            StudentEntry student = StudentQueries.getStudentByID(i.getStudentID());
            if(i.getStatus().equals("scheduled")){
                scheduled += student.getLastName() + ", " + student.getFirstName() + " "+ i.getStudentID() + "\n";
            }
            else{
                listed.add(i);
                waitlisted += student.getLastName() + ", " + student.getFirstName() + " "+ i.getStudentID() + "\n";
            }
        }
        */

    }//GEN-LAST:event_DropStudentButtonActionPerformed

    private void DisplayCourseListOfStudentsDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCourseListOfStudentsDisplayButtonActionPerformed
        // TODO add your handling code here:
        String s = (String) currentSemesterComboBox.getSelectedItem();
        CourseEntry c = (CourseEntry) DisplayCourseListOfStudentsComboBox.getSelectedItem();
        String cc = c.getCourseCode();
        ArrayList<ScheduleEntry> l = ScheduleQueries.getScheduledStudentsByCourse(s,cc);
        String courseDisplay = "Scheduled Students: \n";
        String scheduled = "";
        String waitlisted = "";
        displayCourseListOfStudentsTextArea.setText("L");
        ArrayList<ScheduleEntry> listed = new ArrayList<>();
        for(ScheduleEntry i: l){
            StudentEntry student = StudentQueries.getStudentByID(i.getStudentID());
            if(i.getStatus().equals("scheduled")){
                scheduled += student.getLastName() + ", " + student.getFirstName() + " "+ i.getStudentID() + "\n";
            }
            else{
                listed.add(i);
                waitlisted += student.getLastName() + ", " + student.getFirstName() + " "+ i.getStudentID() + "\n";
            }
        }
        courseDisplay += scheduled;
        courseDisplay += "Waitlisted Students: \n";
        Collections.sort(listed);
        for(ScheduleEntry i: listed){
            StudentEntry student = StudentQueries.getStudentByID(i.getStudentID());
            courseDisplay += student.getLastName() + ", " + student.getFirstName() + " "+ student.getStudentID() + "\n";
        }
        displayCourseListOfStudentsTextArea.setText(courseDisplay);

    }//GEN-LAST:event_DisplayCourseListOfStudentsDisplayButtonActionPerformed

    private void DisplayCourseListOfStudentsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCourseListOfStudentsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayCourseListOfStudentsComboBoxActionPerformed

    private void addStudentFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentFirstNameTextFieldActionPerformed

    private void addStudentSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentSubmitButtonActionPerformed
        // TODO add your handling code here:
        String StudentID = addStudentStudentIDTextField.getText();
        String firstName = addStudentFirstNameTextField.getText();
        String lastName =addStudentLastNameTextField.getText();

        StudentQueries.addStudent(StudentID,firstName, lastName);
        addStudentStatusLabel.setText(firstName +" "+ lastName + " added");

        rebuildStudentComboBoxes();
        
        String s = (String) currentSemesterComboBox.getSelectedItem();
        StudentEntry student = (StudentEntry) DropCourseStudentComboBox1.getSelectedItem();
        if(student != null){
        String ID = student.getStudentID();
        
        ArrayList<ScheduleEntry> classes = ScheduleQueries.getScheduleByStudent(s,ID);
        //ArrayList<ScheduleEntry> classes = ScheduleQueries.getScheduleByStudent(s,ID);
        ArrayList<CourseEntry> cs = new ArrayList<CourseEntry>();
        for(ScheduleEntry i: classes){
            cs.add(new CourseEntry(s,i.getCourseCode(),CourseQueries.getDescription(i.getCourseCode()),CourseQueries.getCourseSeats(s,i.getCourseCode())));
        }
        DropCourseStudentCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(cs.toArray()));
        }
        
        
    }//GEN-LAST:event_addStudentSubmitButtonActionPerformed

    private void addCourseDescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseDescriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourseDescriptionTextFieldActionPerformed

    private void addCourseCourseCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseCourseCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourseCourseCodeTextFieldActionPerformed

    private void addCourseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseSubmitButtonActionPerformed
        // TODO add your handling code here:
        String semester = currentSemesterComboBox.getSelectedItem().toString();
        String courseCode = addCourseCourseCodeTextField.getText();
        String description =addCourseDescriptionTextField.getText();
        int seats = Integer.parseInt(addCourseSeatsSpinner.getValue().toString());
        CourseQueries.addCourse(semester,courseCode,description,seats);
        addCourseStatusLabel.setText("Course added: "+courseCode +": "+ description);
        //rebuildSemesterComboBoxes();
        rebuildStudentComboBoxes();
        rebuildCourseComboBoxes();
        updateCourseDisplay();

        //currentSemesterLabel.setText(String.valueOf(CourseQueries.getCourseSeats("1","1")));
        //currentSemesterLabel.setText(CourseQueries.getAllCourses("67"));
    }//GEN-LAST:event_addCourseSubmitButtonActionPerformed

    private void addSemesterSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterSubmitButtonActionPerformed
        String semester = addSemesterTextfield.getText();
        SemesterQueries.addSemester(semester);
        addSemesterStatusLabel.setText("Semester " + semester + " has been added.");
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_addSemesterSubmitButtonActionPerformed

    private void DropCourseStudentComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropCourseStudentComboBox1ActionPerformed
        // TODO add your handling code here:
        //ArrayList<CourseEntry> Courses = CourseQueries.getAllCourses();
        String s = (String) currentSemesterComboBox.getSelectedItem();
        StudentEntry student = (StudentEntry) DropCourseStudentComboBox1.getSelectedItem();
        String ID = student.getStudentID();
        ArrayList<ScheduleEntry> classes = ScheduleQueries.getScheduleByStudent(s,ID);
        //ArrayList<ScheduleEntry> classes = ScheduleQueries.getScheduleByStudent(s,ID);
        ArrayList<CourseEntry> cs = new ArrayList<CourseEntry>();
        for(ScheduleEntry i: classes){
            cs.add(new CourseEntry(s,i.getCourseCode(),CourseQueries.getDescription(i.getCourseCode()),CourseQueries.getCourseSeats(s,i.getCourseCode())));
        }
        DropCourseStudentCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(cs.toArray()));
    }//GEN-LAST:event_DropCourseStudentComboBox1ActionPerformed

    private void DropCourseStudentSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropCourseStudentSubmitButtonActionPerformed
        // TODO add your handling code here:
        String s = (String) currentSemesterComboBox.getSelectedItem();
        StudentEntry student = (StudentEntry) DropCourseStudentComboBox1.getSelectedItem();
        String ID = student.getStudentID();
        CourseEntry c = (CourseEntry) DropCourseStudentCourseComboBox.getSelectedItem();
        String code = c.getCourseCode();
        ScheduleQueries.removeCourseEntry(ID,code,s);
        ArrayList<ScheduleEntry> students = ScheduleQueries.getScheduledStudentsByCourse(s, code);
        ArrayList<ScheduleEntry> waitlisted = new ArrayList<ScheduleEntry>();
        for(ScheduleEntry stu: students){
            if(stu.getStatus().equals("waitlisted")){
                waitlisted.add(stu);
            }
        }
        String textDisplay = "";
        textDisplay += student.getLastName() + ", " + student.getFirstName() +" "+student.getStudentID() + " has been dropped from " + c.getCourseCode() + "\n";
        Collections.sort(waitlisted);
        if(waitlisted.size() > 0){

            ScheduleQueries.MoveOffWaitlist(waitlisted.get(0));
            StudentEntry addedStudent = StudentQueries.getStudentByID(waitlisted.get(0).getStudentID());
            textDisplay += addedStudent.getLastName() + ", " + addedStudent.getFirstName() + " " +" has been scheduled into " + c.getCourseCode() + "\n";

            ScheduleQueries.addScheduleEntry(new ScheduleEntry(waitlisted.get(0).getSemester(),waitlisted.get(0).getCourseCode(),waitlisted.get(0).getStudentID(),"scheduled",waitlisted.get(0).getTimestamp()));
        }
        DropCourseStudentTextArea.setText(textDisplay);
    }//GEN-LAST:event_DropCourseStudentSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DisplayCourseListOfStudentsComboBox;
    private javax.swing.JButton DisplayCourseListOfStudentsDisplayButton;
    private javax.swing.JComboBox<String> DropCourseCourseComboBox;
    private javax.swing.JButton DropCourseDropButton;
    private javax.swing.JComboBox<String> DropCourseStudentComboBox1;
    private javax.swing.JComboBox<String> DropCourseStudentCourseComboBox;
    private javax.swing.JButton DropCourseStudentSubmitButton;
    private javax.swing.JTextArea DropCourseStudentTextArea;
    private javax.swing.JTextArea DropCourseTextArea;
    private javax.swing.JButton DropStudentButton;
    private javax.swing.JComboBox<String> DropStudentComboBox;
    private javax.swing.JTextArea DropStudentTextArea;
    private javax.swing.JTextField addCourseCourseCodeTextField;
    private javax.swing.JTextField addCourseDescriptionTextField;
    private javax.swing.JSpinner addCourseSeatsSpinner;
    private javax.swing.JLabel addCourseStatusLabel;
    private javax.swing.JButton addCourseSubmitButton;
    private javax.swing.JLabel addSemesterStatusLabel;
    private javax.swing.JButton addSemesterSubmitButton;
    private javax.swing.JTextField addSemesterTextfield;
    private javax.swing.JTextField addStudentFirstNameTextField;
    private javax.swing.JTextField addStudentLastNameTextField;
    private javax.swing.JLabel addStudentStatusLabel;
    private javax.swing.JTextField addStudentStudentIDTextField;
    private javax.swing.JButton addStudentSubmitButton;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JComboBox<String> currentSemesterComboBox;
    private javax.swing.JLabel currentSemesterLabel;
    private javax.swing.JTextArea displayCourseListOfStudentsTextArea;
    private javax.swing.JTextArea displayCoursesTextArea;
    private javax.swing.JButton displayScheduleDisplayButton;
    private javax.swing.JComboBox<String> displayScheduleStudentComboBox;
    private javax.swing.JTextArea displayScheduleTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox<String> scheduleCourseCourseComboBox;
    private javax.swing.JLabel scheduleCourseStatusLabel;
    private javax.swing.JComboBox<String> scheduleCourseStudentComboBox;
    private javax.swing.JButton scheduleCourseSubmitButton;
    // End of variables declaration//GEN-END:variables
}
